# Generated by Django 4.2.1 on 2023-05-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Person name')),
                ('about', models.TextField(verbose_name='Person about')),
                ('img', models.ImageField(upload_to='images', verbose_name='Person image')),
            ],
        ),
    ]
