# Generated by Django 4.2.1 on 2023-05-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about_en',
            field=models.TextField(null=True, verbose_name='Person about'),
        ),
        migrations.AddField(
            model_name='person',
            name='about_hy',
            field=models.TextField(null=True, verbose_name='Person about'),
        ),
        migrations.AddField(
            model_name='person',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='Person about'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Person name'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='Person name'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='Person name'),
        ),
    ]
